ServiceHost = "0.0.0.0"
ServicePort = 8084
Token = "secret_token"

[minio]
Endpoint = "localhost:9000"
BucketName = "images"

[jwt]
Token = "amogus"
ExpiresIn = "24h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"